
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcgzdqtdarjunpkoyyus.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjZ3pkcXRkYXJqdW5wa295eXVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MzE1NjQsImV4cCI6MjA1OTEwNzU2NH0.Y7Ww_Sak58sm7OGITAIgHWGBa_UkaFJ9Ga3hMktbQSA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
